### ISSUE TITLE
Compiling ClojureScript with advanced optimizations takes a lot of time

### ISSUE THREAD

**Issue by xavi** [heroku/heroku-buildpack-clojure#25]
Deploying my open-source noir-auth-app project ( https://github.com/xavi/noir-auth-app/blob/heroku-deploy/project.clj ) to Heroku takes 6–7 minutes. Approximately half of this time is spent compiling less than 200 lines of ClojureScript with `:advanced` optimizations.

The deployment is done via uberjar, as I understand this is now the recommended deployment method, and lein-cljsbuild Leiningen hooks are configured (see project.clj linked above for details).

Taking into account that running `lein uberjar` in my MBP (2.26 GHz Intel Core 2 Duo) takes less than 1 minute and a half, is it normal that deploying to Heroku takes more than 6 minutes?

Looking at the logs, it seems the problem is the `:advanced` optimizations build, which takes more than 3 minutes in Heroku, but less than 30 seconds in my MBP (in contrast, the other configured ClojureScript build, which uses `:whitespace` optimizations, takes around the same time, ~16 s, in both my MBP and Heroku, actually a few seconds less in Heroku).

What's even worse is that I'm also working on another project (not open-source) with just 50 more lines of ClojureScript and Heroku cannot complete the deployment in 15 minutes and times out (if there's luck, it takes nearly 7 minutes to compile the ClojureScript with advanced optimizations, and nearly 15 minutes to complete the deployment). (In my MBP, `lein uberjar` in this project takes 1 min 37 s.)

Is there some problem with `:advanced` ClojureScript compilation in the Heroku buildpack for Clojure? Am I doing something wrong?

Thanks in advance.

**Comment by paxan** [comment]
I was told Heroku dynos used for build have 1Gb RAM. Perhaps that causes memory issues?
Try creating a one-off `2X` dyno and downloading src to it and build it like Heroku does... Maybe logs will reveal the memory trouble. Just an idea.

**Comment by jkutner** [comment]
In cases where the build is too heavy, we recommend using the Heroku Leiningen plugin to deploy locally compiled assets. https://devcenter.heroku.com/articles/deploying-clojure-applications-with-the-heroku-leiningen-plugin
