### ISSUE TITLE
Support for Oracle JDK?

### ISSUE THREAD

**Issue by laczoka** [heroku/heroku-buildpack-clojure#41]
Is there any chance that the following piece of work will be incorporated in the official clojure buildpack?

https://github.com/trautonen/heroku-buildpack-oracle-java

**Comment by jkutner** [comment]
No, there is not a plan to incorporate the Oracle JDK in an official capacity. There are a number of legal and technical concerns.

Is there some feature you need that OpenJDK does not provide?

If one were to download the Oracle JDK, put it on S3, and set the config var `JDK_URL_1_8` config var like so:

```
$ heroku config:set JDK_URL_1_8="http://s3.../oraclejdk.tar.gz"
```

Then, you would be able to include it yourself.

**Comment by laczoka** [comment]
Thanks!
> Is there some feature you need that OpenJDK does not provide?
Not really, but it is the JDK version we use internally at the minute.
