### ISSUE TITLE
JVM_OPTS clashes with JAVA_OPTS set by heroku-buildpack-jvm-common

### ISSUE THREAD

**Issue by paxan** [heroku/heroku-buildpack-clojure#43]
As things stand now, `bin/compile` generates `.profile.d/clojure.sh` that [exports `JVM_OPTS` var with `Xmx=400m`.][1]

[As of recently,][2] the presence of this var has started to clash with the logic inside `.profile.d/jvmcommon.sh` which ends up not setting `JAVA_OPTS` with dyno-specific Xmx values.

[1]: https://github.com/heroku/heroku-buildpack-clojure/blob/92020d2fbd0d11d7050c9ff1dd31d05f0e386cb3/bin/compile#L156-L162
[2]: https://github.com/heroku/heroku-buildpack-jvm-common/commit/abe0c06ca992345e848aef24fd901d87a53f18bc#commitcomment-13035179

**Comment by jkutner** [comment]
Ack, sorry about this. I think the best thing for us to do in the short term is just remove these two lines from jvm-common:
https://github.com/heroku/heroku-buildpack-jvm-common/blob/master/opt/jvmcommon.sh#L26-L27

Then I'll fix the clojure buildpack so that JVM_OPTS is set dynamically (Just like the other env vars in jvm-common). Does that sound reasonable?

**Comment by paxan** [comment]
Seems like that would fix our issue. Checking...

**Comment by paxan** [comment]
Ah... still doesn't work, but that's because `https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/jvm-common.tgz` still has the problematic version of `jvmcommon.sh`

**Comment by jkutner** [comment]
Oh sorry, yes we have to release it. If you want to give it a try now, you can set this config var (note the "jkutner" part instead of "heroku"):

```
$ heroku config:set JVM_COMMON_BUILDPACK="https://codon-buildpacks.s3.amazonaws.com/buildpacks/jkutner/jvm-common.tgz"
```

Let me know if that works, but I'll probably release here in a bit either ways.

**Comment by jkutner** [comment]
I've released the regular default jvm-common, so this should be resolved for you. I'll leave this ticket open and close it when I've fixed JVM_OPTS in this buildpack.

**Comment by paxan** [comment]
Ok that worked! (that's with custom JVM_COMMON_BUILDPACK)
And thanks for releasing the jvmcommon.

Sounds like I don't need to pass JAVA_OPTS to `java ...` in Procfile anymore... It should pickup JAVA_TOOL_OPTIONS. Right?

**Comment by jkutner** [comment]
Correct. You could use JAVA_OPTS for things that are specific to your app if need or if you just preferred to keep them out of the Procfile. But otherwise, every Java process will pick up JAVA_TOOL_OPTIONS (with the exception of Java procs in one-off dynos started with `heroku run`).

**Comment by jkutner** [comment]
I've fixing this by removing JVM_OPTS entirely. It just gets in the way of JAVA_OPTS and JAVA_TOOL_OPTIONS and doesn't provide any advantages.

**Comment by paxan** [comment]
That makes total sense.
