### ISSUE TITLE
Make node available at build time

### ISSUE THREAD

**Issue by jkutner** [heroku/heroku-buildpack-clojure#44]
Currently, the way to make `node` available at build time is using multi-pack support like this:

```
$ heroku buildpacks:clear
$ heroku buildpacks:add https://github.com/heroku/heroku-buildpack-nodejs
$ heroku buildpacks:add https://github.com/heroku/heroku-buildpack-clojure
```

But this requires the presence of a minimal `package.json` file with at least the contents:

``` json
{}
```

For apps that use [lein-npm](https://github.com/RyanMcG/lein-npm) this is a problem in part because lein-npm generates the `package.json`on the fly (during the build), which causes the nodejs buildpack's detection to fail.

It would be preferable if the nodejs buildpack was not necessary, or if there were an easier way to use it.

See also: http://stackoverflow.com/questions/32693625/add-nodejs-to-a-clojure-app-in-heroku/32695104

**Comment by jkutner** [comment]
I've created [this branch as a prototype](https://github.com/heroku/heroku-buildpack-clojure/tree/nodejs). To test it, run:

```
$ heroku buildpacks:set https://github.com/heroku/heroku-buildpack-clojure#nodejs 
```

I'd still like to add some kind of Node.js version detection, but for now, it defaults to 4.0.0 and can be configured with `heroku config:set NODEJS_VERSION="..."`.

**Comment by TerjeNorderhaug** [comment]
Thanks for promoting this issue. I have successfully resorted to a custom [bin/build](https://github.com/TerjeNorderhaug/cljsnode/tree/master/bin) file to make the Clojure buildpack also install NodeJS, but that's a bit of a hack.

**Comment by jkutner** [comment]
@TerjeNorderhaug did the nodejs branch not work for you? if not, can you explain why so we can improve it?

I'd still like to get this into master (and the official buildpack), but wanted to make sure it works for many different cases.

**Comment by jkutner** [comment]
This is in master now, and I've added better support for @TerjeNorderhaug's type of app. would love it if you could test this out with:

```
$ heroku buildpacks:add https://github.com/heroku/heroku-buildpack-clojure
```
