### ISSUE TITLE
Boot support

### ISSUE THREAD

**Issue by malchmih** [heroku/heroku-buildpack-clojure#45]
There is another build tool for Clojure, called [Boot](http://boot-clj.com/). It's not as popular now as Leiningen now, but its great. Is it possible to add support for it?

**Comment by jkutner** [comment]
I recommend the third-party Boot buildpack from the folks at Upworthy:
https://github.com/upworthy/heroku-buildpack-boot

**Comment by malchmih** [comment]
Great, thanks!
