### ISSUE TITLE
Could not transfer artifact lein-cprop:lein-cprop:pom:1.0.1 from/to central

### ISSUE THREAD

**Issue by erjoalgo** [heroku/heroku-buildpack-clojure#48]
I'm new and I'm not sure if this is an issue with my cf, with this buildpack, or something else, but I thought I'd try here:

```
[my-hostname]$ cf push
  Using manifest file /home/my-login/repos/routes-diff-cl/manifest.yml
  
  Using stack cflinuxfs2...
  OK
  Updating app routes-diff-cl in org my-first-name.my-last-user@example.com / space dev as my-first-name.my-last-user@example.com...
  OK
  
  Uploading routes-diff-cl...
  Uploading app files from: /home/my-login/repos/routes-diff-cl
  Uploading 7.2M, 3272 files
  Done uploading               
  OK
  
  Stopping app routes-diff-cl in org my-first-name.my-last-user@example.com / space dev as my-first-name.my-last-user@example.com...
  OK
  
  Starting app routes-diff-cl in org my-first-name.my-last-user@example.com / space dev as my-first-name.my-last-user@example.com...
  -----> Downloaded app package (47M)
  Cloning into '/tmp/buildpacks/heroku-buildpack-clojure'...
  -----> Installing OpenJDK 1.8... done
  -----> Installing Leiningen
  Downloading: leiningen-2.6.1-standalone.jar
  Writing: lein script
  -----> Building with Leiningen
  Running: lein uberjar
  Could not transfer artifact lein-cprop:lein-cprop:pom:1.0.1 from/to central (https://repo1.maven.org/maven2/): java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
  This could be due to a typo in :dependencies or network issues.
  If you are behind a proxy, try setting the 'http_proxy' environment variable.
  !     Failed to build.
  Staging failed: Buildpack compilation step failed
  
  FAILED
  BuildpackCompileFailed
  
  TIP: use 'cf logs routes-diff-cl --recent' for more information
  [my-hostname]$ 
```

cf logs doesn't show any more information than what is above. I can build the jar locally.

**Comment by jkutner** [comment]
This is probably happening because there is no `/etc/ssl/certs/java/cacerts` on cf. This buildpack creates a symlink to that file (by way of the [jvm-common buildpack](https://github.com/heroku/heroku-buildpack-jvm-common/blob/master/bin/java#L69-L75)). Without it, there are no trusted certs.

I'll create a pull request for jvm-common so that it does not mess with the `cacerts` file if `/etc/ssl/certs/java/cacerts` does not exist. But may be a few days.

**Comment by erjoalgo** [comment]
Please take your time. Would be greatly appreciated

**Comment by jkutner** [comment]
I forgot to mention, but this was released last week. Let me know if you still have problems.

**Comment by erjoalgo** [comment]
Thanks for this, I can confirm that I'm no longer getting the `Buildpack compilation step failed` error. I'm still unable to start the app (failed to start accepting connections), even though I can build an uberjar and start locally, but hopefully this is an error on my end.

**Comment by erjoalgo** [comment]
Just to confirm, it was an error on my end that was resolved.
