### ISSUE TITLE
clojure / clj command not available during build

### ISSUE THREAD

**Issue by AlexAti** [heroku/heroku-buildpack-clojure#59]
During build (or with the "heroku run bash" command), clojure is not available as a command. With the new tooling provided by clojure 1.9 and clojure 1.10 (https://clojure.org/reference/deps_and_cli), more packages are depending on it; so it would be useful to have the command available in the build pack.

More specifically, if dependencies are specified through a deps.edn file that is loaded during uberjar creation with lein-tool-deps (https://github.com/RickMoynihan/lein-tools-deps), which enables to reference github and gitlab repos, the process fails, stating the following error:

```
remote:        clojure.lang.ExceptionInfo: Could not find clojure executable
remote:         at clojure.core$ex_info.invokeStatic (core.clj:4617)
remote:            clojure.core$ex_info.invoke (core.clj:4617)
remote:            lein_tools_deps.env$clojure_exe.invokeStatic (env.clj:22)
remote:            lein_tools_deps.env$clojure_exe.invoke (env.clj:16)
remote:            lein_tools_deps.env$scrape_clojure_env.invokeStatic (env.clj:28)
remote:            lein_tools_deps.env$scrape_clojure_env.invoke (env.clj:24)
(etc.)
```

**Comment by jkutner** [comment]
@AlexAti I agree it makes sense to include `bin/clojure` and `bin/clj`. I don't know much about how they are built/installed though (i.e. are they thin wrappers around a Java command or something more complex).

I'll investigate this, but if you're interested in working on it yourself, I would definitely accept a PR.

Thanks for opening the issue.

**Comment by AlexAti** [comment]
Hey,

I'm trying to get it to work in https://github.com/AlexAti/heroku-buildpack-clojure/commit/4097c05b7828b0c35735e5bdc17d93c9738a5674 but for some reason the installed /bin/clojure can't be seen by leiningen. I will keep trying to get it to work but perhaps you have an idea of what I'm doing wrong? I don't know a lot about these buildpacks...

Thanks!

**Comment by AlexAti** [comment]
Hey,

I fixed the issue at https://github.com/AlexAti/heroku-buildpack-clojure/commit/9ae2bbe4fc16670eb9da08239f455380d7475acb.
As an example, this minimal project https://github.com/AlexAti/lein-with-deps-project does not deploy with the current buildpack, but using https://github.com/AlexAti/heroku-buildpack-clojure.git as buildpack it deploys correctly.

I have thus created PR on https://github.com/heroku/heroku-buildpack-clojure/pull/60 ! So I will now close this issue.
